rm -rf dir ../data
rm -rf dir ../src/DXGame.Api/bin
rm -rf dir ../src/DXGame.Api/obj
rm -rf dir ../src/DXGame.Common/bin
rm -rf dir ../src/DXGame.Common/obj
rm -rf dir ../src/DXGame.ReadModel/bin
rm -rf dir ../src/DXGame.ReadModel/obj
rm -rf dir ../src/DXGame.Services.Playroom/bin
rm -rf dir ../src/DXGame.Services.Playroom/obj
